# Generated by Django 3.0.7 on 2020-07-10 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0004_auto_20200710_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='books',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='books_credit', to='p_library.Exchange'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='full_name',
            field=models.CharField(default='', max_length=25, null=True),
        ),
    ]
