# Generated by Django 3.0.7 on 2020-07-12 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0005_auto_20200710_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='books',
        ),
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, upload_to='covers/'),
        ),
    ]
