# Generated by Django 3.0.7 on 2020-07-12 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0008_auto_20200712_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p_library.Book'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='friend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p_library.Friend'),
        ),
    ]
